from dataclasses import dataclass
from uuid import UUID, uuid4
from datetime import datetime
from typing import Protocol, List, Optional
from src.domain.models import Vehicle, VehicleStatus


class VehicleRepository(Protocol):
    def add(self, v: Vehicle): ...
    def list_by_status_ordered(self, status: VehicleStatus): ...
    def get(self, vehicle_id: UUID) -> Optional[Vehicle]: ...
    def update(self, v: Vehicle) -> Vehicle: ...
    def list_available(self) -> List[Vehicle]: ...
    def list_sold(self) -> List[Vehicle]: ...
    def mark_reserved(self, vehicle_id: UUID, reserved_by: str) -> None: ...
    def mark_sold(self, vehicle_id: UUID) -> None: ...