"""add reserved_by and reserved_at

Revision ID: 7e42611e268e
Revises: 862db319915c
Create Date: 2025-09-27 21:11:46.266932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e42611e268e'
down_revision: Union[str, None] = '862db319915c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('reserved_by', sa.String(length=120), nullable=True))
    op.add_column('vehicles', sa.Column('reserved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'reserved_at')
    op.drop_column('vehicles', 'reserved_by')
    # ### end Alembic commands ###
